#!/bin/bash

# auto-download latest release bin
if ! [ -d ".bin" ] || ! [ -f ".bin/wish-compiler" ]; then
    mkdir .bin
    url=$(curl -s https://api.github.com/repos/dhleong/wish-compiler/releases/latest \
        | grep "browser_download_url" \
        | cut -d '"' -f 4)
    curl $url -Lo .bin/wish-compiler
    chmod +x .bin/wish-compiler
fi

.bin/wish-compiler "$@"
